<table class="table table-striped table-bordered table-hover">
<?php
foreach($roles as $r) {
    ?>
<tr>
    <td><?php echo $r->getName();?>
        <?php if(count($r->getResources())){
            ?>
<br>
        <?php
        foreach($r->getResources() as $p){
            ?>
            <small><?php echo $p;?></small>
        <?php
        }
        } ?>
    </td>
    <td>
        <button role_id="<?php echo $r->getId();?>" type="button" class="btn btn-outline btn-default btn-xs role-resources-btn">
            <i class="fa fa-sitemap"></i>
        </button>
        <button role_id="<?php echo $r->getId();?>" type="button" class="btn btn-outline btn-danger btn-xs delete-role-btn">
            <i class="fa fa-times-circle"></i>
        </button>
    </td>
</tr>
<?php
    }
?>
</table>

<script>
  $(document).ready(function(){
      $(role.opt.deleteBtn).confirm({
          'title':'Confirmar:',
          'confirm':function(button){
                var role_id = $(button).attr("role_id");
              role.delete(role_id);
          },
          'confirmButton': "Si",
          'cancelButton': "No",
          'text': "Eliminar Role?"
      });
  });
</script>
