<table class="table table-striped table-bordered table-hover">
    <?php foreach($resources as $r){ ?>
    <tr>
        <td>
                 <?php echo $r->getLabel();?>
                <br>
                <small>
                <?php echo $r->getPath();?>
                </small>
        </td>
        <td>
            <button resource_id="<?php echo $r->getId();?>" type="button" class="btn btn-outline btn-danger btn-xs delete-resource-btn">
                <i class="fa fa-times-circle"></i>
            </button>
        </td>
    </tr>
    <?php } ?>
</table>
<script>
    $(document).ready(function(){
        $(recurso.opt.deleteBtn).confirm({
            'title':'Confirmar:',
            'confirm':function(button){
                var resource_id = $(button).attr("resource_id");
                recurso.delete(resource_id);
            },
            'confirmButton': "Si",
            'cancelButton': "No",
            'text': "Eliminar Recurso?"
        });
    });
</script>
